version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ilis_postgres
    restart: always
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
